In [13]:
import pandas as pd

In [14]:
df = pd.read_csv("Titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
df.drop(["PassengerId", "Name", "Ticket"], axis=1, inplace=True)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [16]:
null = df.isnull().sum()
ratio = null / df.shape[0]
pd.DataFrame({"nulls_sum": null, "Ratio": ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
nulls_sum,0.0,0.0,0.0,177.000000,0.0,0.0,0.0,687.000000,2.000000
Ratio,0.0,0.0,0.0,0.198653,0.0,0.0,0.0,0.771044,0.002245

In [17]:
df = df.dropna(subset= ['Embarked'])

In [18]:
df = df.drop("Cabin", axis = 1)

In [19]:
df['Age'] = df["Age"].fillna(df['Age'].median())

In [20]:
null = df.isnull().sum()
ratio = null / df.shape[0]
pd.DataFrame({"nulls_sum": null, "Ratio": ratio}).T

           Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
nulls_sum       0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0
Ratio           0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0

In [21]:
x = df.drop("Survived", axis=1)
y = df[["Survived"]]

In [22]:
cols = ['Pclass', 'Survived', 'SibSp', 'Sex', 'Parch', 'Embarked']
df[cols] = df[cols].astype('category')
pd.DataFrame(df.dtypes).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,category,category,category,float64,category,category,float64,category

In [23]:
nums_col = df.select_dtypes("number").columns
nums_col

Index(['Age', 'Fare'], dtype='str')

In [24]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
# scaler.fit(x[nums_col])
x[nums_col] = scaler.fit_transform(x[nums_col])
x[nums_col]

          Age      Fare
0    0.271174  0.014151
1    0.472229  0.139136
2    0.321438  0.015469
3    0.434531  0.103644
4    0.434531  0.015713
..        ...       ...
886  0.334004  0.025374
887  0.233476  0.058556
888  0.346569  0.045771
889  0.321438  0.058556
890  0.396833  0.015127

[889 rows x 2 columns]

In [25]:
x.head()

   Pclass     Sex       Age  SibSp  Parch      Fare Embarked
0       3    male  0.271174      1      0  0.014151        S
1       1  female  0.472229      1      0  0.139136        C
2       3  female  0.321438      0      0  0.015469        S
3       1  female  0.434531      1      0  0.103644        S
4       3    male  0.434531      0      0  0.015713        S

In [26]:
str_cols = ["Sex", "Embarked"]

In [27]:
from category_encoders import OneHotEncoder
encoder = OneHotEncoder(cols = str_cols, drop_invariant= True)
x = encoder.fit_transform(x)

In [28]:
x.head()

,Pclass,Sex_1,Sex_2,Age,SibSp,Parch,Fare,Embarked_1,Embarked_2,Embarked_3
0,3,1,0,0.271174,1,0,0.014151,1,0,0
1,1,0,1,0.472229,1,0,0.139136,0,1,0
2,3,0,1,0.321438,0,0,0.015469,1,0,0
3,1,0,1,0.434531,1,0,0.103644,1,0,0
4,3,1,0,0.434531,0,0,0.015713,1,0,0

In [29]:
import plotly.express as px
import plotly.graph_objects as go

In [44]:
fig = px.pie(df, names="Survived",
            title="<b> Survived </b>",
            color_discrete_sequence=px.colors.qualitative.Pastel,
            hole=0.4)
fig.update_traces(textinfo="percent+label")
fig.update_layout(annotations = [dict(text = "Survived", font_size = 20, x = 0.5, y = 0.5, showarrow=False)])
fig.show()

In [ ]:
# pip install nbformat

Requirement already satisfied: nbformat in d:\DEPI\Task\DEPI-BNS5_AIS2_S1\.venv\Lib\site-packages (5.11.1)
Requirement already satisfied: fastjsonschema>=2.15 in d:\DEPI\Task\DEPI-BNS5_AIS2_S1\.venv\Lib\site-packages (from nbformat) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in d:\DEPI\Task\DEPI-BNS5_AIS2_S1\.venv\Lib\site-packages (from nbformat) (4.26.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in d:\DEPI\Task\DEPI-BNS5_AIS2_S1\.venv\Lib\site-packages (from nbformat) (5.9.1)
Requirement already satisfied: traitlets>=5.1 in d:\DEPI\Task\DEPI-BNS5_AIS2_S1\.venv\Lib\site-packages (from nbformat) (5.15.1)
Requirement already satisfied: attrs>=22.2.0 in d:\DEPI\Task\DEPI-BNS5_AIS2_S1\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in d:\DEPI\Task\DEPI-BNS5_AIS2_S1\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in d:\DEPI\Task\DEPI-BNS5_AIS2_S1\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in d:\DEPI\Task\DEPI-BNS5_AIS2_S1\.venv\Lib\site-packages (from jsonschema>=2.6->nbformat) (2026.6.3)
Requirement already satisfied: platformdirs>=2.5 in d:\DEPI\Task\DEPI-BNS5_AIS2_S1\.venv\Lib\site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.10.1)
Note: you may need to restart the kernel to use updated packages.

In [36]:
px.histogram(df, x = "Survived", color="Sex", title="<b> Survived based on Gender</b>", barmode="group")

In [39]:
fig = px.scatter(df, x = "Age", y = "Fare", title="Scatter plot", opacity=0.2)
fig.show()