In [1]:
import pandas as pd

In [63]:
df = pd.read_csv("Titanic.csv")

In [ ]:
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [64]:
df.drop(["PassengerId", "Name", "Ticket"], axis=1, inplace=True)
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [22]:
from config import drop_columns
def drop_cols(df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
    """
    """
    return df.drop(columns = cols)

In [23]:
df = drop_cols(df, drop_columns)

In [24]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

<h1>check data type</h1>

In [25]:
df.dtypes

Survived      int64
Pclass        int64
Sex             str
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Cabin           str
Embarked        str
dtype: object

In [27]:
dtypes = df.dtypes
n_uniq = df.nunique()
pd.DataFrame({"Dtypes":dtypes, "Num_uniqe": n_uniq })

           Dtypes  Num_uniqe
Survived    int64          2
Pclass      int64          3
Sex           str          2
Age       float64         88
SibSp       int64          7
Parch       int64          7
Fare      float64        248
Cabin         str        147
Embarked      str          3

In [31]:
from ps import uniqe
uniqe(df)

           Dtypes  Num_uniqe
Survived    int64          2
Pclass      int64          3
Sex           str          2
Age       float64         88
SibSp       int64          7
Parch       int64          7
Fare      float64        248
Cabin         str        147
Embarked      str          3

In [65]:
cols = ['Pclass', 'Survived', 'SibSp', 'Sex', 'Parch', 'Embarked']
df[cols] = df[cols].astype('category')
pd.DataFrame(df.dtypes).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,category,category,category,float64,category,category,float64,str,category

In [66]:
null = df.isnull()
null

     Survived  Pclass    Sex    Age  SibSp  Parch   Fare  Cabin  Embarked
0       False   False  False  False  False  False  False   True     False
1       False   False  False  False  False  False  False  False     False
2       False   False  False  False  False  False  False   True     False
3       False   False  False  False  False  False  False  False     False
4       False   False  False  False  False  False  False   True     False
..        ...     ...    ...    ...    ...    ...    ...    ...       ...
886     False   False  False  False  False  False  False   True     False
887     False   False  False  False  False  False  False  False     False
888     False   False  False   True  False  False  False   True     False
889     False   False  False  False  False  False  False  False     False
890     False   False  False  False  False  False  False   True     False

[891 rows x 9 columns]

In [67]:
null = df.isnull().sum()
ratio = null / df.shape[0]
pd.DataFrame({"nulls_sum": null, "Ratio": ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
nulls_sum,0.0,0.0,0.0,177.000000,0.0,0.0,0.0,687.000000,2.000000
Ratio,0.0,0.0,0.0,0.198653,0.0,0.0,0.0,0.771044,0.002245

In [68]:
df = df.dropna(subset= ['Embarked'])

In [69]:
df = df.drop("Cabin", axis = 1)

In [71]:
df['Age'] = df["Age"].fillna(df['Age'].median())

In [72]:
null = df.isnull().sum()
ratio = null / df.shape[0]
pd.DataFrame({"nulls_sum": null, "Ratio": ratio}).T

           Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
nulls_sum       0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0
Ratio           0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0

In [75]:
num_cols = df.select_dtypes("number").columns
num_cols = ['Age', 'Fare']